version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.3
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms256m -Xmx1024m"
  app:
    build:
      context: .
      args:
        API_URL: "http://localhost"
    environment:
      NODE_ENV: production
      ELASTIC_URL: "elasticsearch:9200"
    ports:
      - 80:8080
    depends_on:
      - elasticsearch
